title: Consorzio Copernicus Academy
email: consorzioita_ca@pro-pec.it
description: >- # this means to ignore newlines until "baseurl:"
  Consorzio Italiano per la Copernicus Academy
baseurl: "/"
url: "https://www.consorzioca.it"
email: "consorzioita_ca@pro-pec.it"
pec: "consorzioita_ca@pro-pec.it"
address: "Corso Duca Degli Abruzzi 24 - 10129 Torino (TO)"

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Navigation
navigationLinks:
 - {permalink: "/soci/", text: "Soci"}
 - {permalink: "/amministratori/", text: "Amministratori"}
 - {permalink: "/statuto/", text: "Statuto"}
 - {permalink: "/contatti/", text: "Contatti"}